//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stile.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body must be of the form &apos;x =&gt; x.&lt;...&gt;&apos; but was &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionExtensions_GetBodySubstring_BodyForm {
            get {
                return ResourceManager.GetString("ExpressionExtensions_GetBodySubstring_BodyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have exactly one expression parameter but had {0}..
        /// </summary>
        internal static string ExpressionExtensions_GetBodySubstring_ParameterCount {
            get {
                return ResourceManager.GetString("ExpressionExtensions_GetBodySubstring_ParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ExpressionFormatProvider_Format_Invalid {
            get {
                return ResourceManager.GetString("ExpressionFormatProvider_Format_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument of type {0} must have a {1}.
        /// </summary>
        internal static string FaultSpecification_ctor_filterBuilder {
            get {
                return ResourceManager.GetString("FaultSpecification_ctor_filterBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial token {0} must be in the set of nonterminals..
        /// </summary>
        internal static string Grammar_InitialToken {
            get {
                return ResourceManager.GetString("Grammar_InitialToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables and terminals should not overlap but had {0} {1} in common:\r\n{2}.
        /// </summary>
        internal static string Grammar_Overlap {
            get {
                return ResourceManager.GetString("Grammar_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to add token &apos;{0}&apos; with alias &apos;{1}&apos;, but found a symbol with that token and alias &apos;{2}&apos; instead..
        /// </summary>
        internal static string GrammarBuilder_AliasCollision {
            get {
                return ResourceManager.GetString("GrammarBuilder_AliasCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These edges had vertices that were not in the graph:{0}{1}.
        /// </summary>
        internal static string GraphExtensions_VerifyAreOn_EdgesNotInGraph {
            get {
                return ResourceManager.GetString("GraphExtensions_VerifyAreOn_EdgesNotInGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument of type {0} must be convertible to {1}.
        /// </summary>
        internal static string Specification_ExpectationBuilderState {
            get {
                return ResourceManager.GetString("Specification_ExpectationBuilderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , column {0}.
        /// </summary>
        internal static string ValidateArgument_TryGetParameterName_Column {
            get {
                return ResourceManager.GetString("ValidateArgument_TryGetParameterName_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ValidateArgument_TryGetParameterName_Delimiter {
            get {
                return ResourceManager.GetString("ValidateArgument_TryGetParameterName_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one of {{{0}}}.
        /// </summary>
        internal static string ValidateArgument_TryGetParameterName_OneOf {
            get {
                return ResourceManager.GetString("ValidateArgument_TryGetParameterName_OneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string ValidateArgument_TryGetParameterName_ParameterFormat {
            get {
                return ResourceManager.GetString("ValidateArgument_TryGetParameterName_ParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , validated at line {0}.
        /// </summary>
        internal static string ValidateArgument_TryGetParameterName_ValidateAtLine {
            get {
                return ResourceManager.GetString("ValidateArgument_TryGetParameterName_ValidateAtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Could not determine the argument name via reflection, but a null was passed of type {0}).
        /// </summary>
        internal static string ValidateArgument_ValidateArgumentIsNotNull {
            get {
                return ResourceManager.GetString("ValidateArgument_ValidateArgumentIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string ValidateArgument_ValidateArgumentIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidateArgument_ValidateArgumentIsNotNullOrEmpty", resourceCulture);
            }
        }
    }
}
