//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stile.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s.
        /// </summary>
        internal static string PrintExtensions_Pluralize {
            get {
                return ResourceManager.GetString("PrintExtensions_Pluralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string PrintExtensions_ReadableEmpty {
            get {
                return ResourceManager.GetString("PrintExtensions_ReadableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;null&gt;.
        /// </summary>
        internal static string PrintExtensions_ReadableNull {
            get {
                return ResourceManager.GetString("PrintExtensions_ReadableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;null&gt;&quot;.
        /// </summary>
        internal static string PrintExtensions_ReadableNullString {
            get {
                return ResourceManager.GetString("PrintExtensions_ReadableNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintExtensions_ToDebugString_.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_ {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_CloseQuote {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_CloseQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_False {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_OpenQuote {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_OpenQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_ReplaceN {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_ReplaceN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_ReplaceR {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_ReplaceR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_ReplaceT {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_ReplaceT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string PrintExtensions_ToDebugString_True {
            get {
                return ResourceManager.GetString("PrintExtensions_ToDebugString_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpanExtensions_ToReadableUnits_.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Day {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Hour {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minus.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Minus {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Minute {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Ms {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Second {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Seconds {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tick.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_Tick {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpan.Zero.
        /// </summary>
        internal static string TimeSpanExtensions_ToReadableUnits_TimeSpanZero {
            get {
                return ResourceManager.GetString("TimeSpanExtensions_ToReadableUnits_TimeSpanZero", resourceCulture);
            }
        }
    }
}
